### ISSUE TITLE
Exception "unhandled KeyError" 'HOME'

### ISSUE THREAD

**Issue by charles2268** [bkdwei/kdssh#1]
![default](https://user-images.githubusercontent.com/39716978/53851520-ebface80-3ff9-11e9-80f5-1e45288b01e5.PNG)

在eric6中按F2执行kdssh报这个错，请问是什么原因呀？谢谢

**Comment by bkdwei** [comment]
home是linux下的系统环境变量，是用户的主目录/home/用户名，类似于windows的c:\Users\用户名。
你可以将os.environ['HOME']修改为os.path.expanduser('~') 即可。os.path.expanduser('~')适用于任何系统，os.environ['HOME']适用于获取linux下的用户主目录。
